plugins {
    id("dev.nx.gradle.project-graph") version("0.1.10")
}
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.2.1/samples
 */

allprojects {
  repositories {
    mavenCentral()
    maven { url = uri("https://jitpack.io") }
    maven { url = uri("https://repo.spring.io") }
    maven { url = uri("https://github.com/psiegman/mvn-repo/raw/master/releases") } // epublib
   // maven { url = uri("https://maven.oracle.com") }
  }
  apply {
      plugin("dev.nx.gradle.project-graph")
  }
}
/*allprojects {
  group = "sv.com.clip" // Ensure this is NOT null
  version = "1.0.0"
}*/

