services:
  postgres:
    image: pgvector/pgvector:pg15  # O la versión más reciente disponible en 2026
    container_name: postgres_local
    environment:
      POSTGRES_DB: clip
      POSTGRES_USER: clip_user
      POSTGRES_PASSWORD: clip_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_local
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
  chatterbox-tts:
    image: travisvn/chatterbox-tts-api:latest
    container_name: chatterbox-api
    profiles:
      - tts-manual
    ports:
      - "5123:5123"
    environment:
      - DEVICE=cpu  # Cambia a 'cuda' si tienes GPU NVIDIA
    restart: unless-stopped
volumes:
  postgres_data:
