events {}

http {
  upstream kokoro {
    server kokoro-tts:3000;  # Kokoros usa 3000, no 8880
  }

  server {
    listen 80;

    location / {
      proxy_pass http://kokoro;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_buffering off;  # importante para streaming NDJSON
    }
  }
}