clip:
  tts:
    base-url: ${TTS_BASE_URL:http://localhost:8880}

storage:
  location: /var/opt/clip/uploads

server:
  compression:
    # 1. Activar la compresión
    enabled: true
    # 2. Tipos de archivos que deben comprimirse (JSON es el más importante para ti)
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/plain
      - text/css
    # 3. Tamaño mínimo (en bytes) para aplicar compresión.
    # Menos de 1KB no vale la pena comprimir por el overhead de CPU.
    min-response-size: 1024

  servlet:
    session:
      cookie:
        name: CLIP_API_SESSIONID

  tomcat:
    max-swallow-size: -1 # Permitir que el servidor "trague" la solicitud aunque exceda el límite

spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          keep-alive: 5m
          model: gemma2:2b #qwen2.5:1.5b #llama3
          temperature: 0.2 #0.3 # Baja temperatura para traducciones más precisas
  servlet:
    multipart:
      max-file-size: 500MB # Tamaño máximo de un solo archivo (ejemplo: 50MB)
      max-request-size: 500MB # Tamaño máximo total de la solicitud (archivos + datos)
      file-size-threshold: 10MB # Umbral para escribir a disco en lugar de RAM
  application:
    name: api
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/clip
    username: clip_user
    password: clip_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update #validate #update
    show-sql: true
    properties:
      hibernate:
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 100 # Loguea queries que tarden más de 100ms
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
        generate_statistics: true # Muestra cuánto tarda cada query real en SQL

logging:
  level:
    #root: DEBUG
    org:
      #springframework: DEBUG
      hibernate:
        stat: DEBUG
      flywaydb: DEBUG

